// Sprite Text adapter support: explicit controller dependency facades.
// Controllers use these facets instead of constructing ad hoc scope dispatchers.
(() => {
    'use strict';

    LiveTranslatorDefine({
        name: 'adapters.spriteText.controllerFacades',
        factory() {

    function createSpriteTextControllerFacades(scope = {}) {
        return Object.freeze({
            bitmapObservation: bindScopeMethods(scope, [
                'recordBitmapDrawText',
                'getBitmapDrawRecordStatus',
                'normalizeBitmapDrawRecordStatus',
                'createTextOpFromPayload',
                'recordBitmapMutation',
                'installBitmapMutationObserver',
                'handleObservedBitmapMutation',
                'recordPaintOp',
                'deriveMutationRect',
            ]),
            bitmapOwnership: bindScopeMethods(scope, [
                'installSpriteBitmapObserver',
                'attachBitmapOwner',
                'detachBitmapOwner',
                'claimSpriteBitmapSurface',
                'releaseSpriteBitmapSurface',
                'isBitmapOwned',
                'getBitmapOwners',
                'isSpriteLifecycleRelevant',
                'hasActiveSpriteTextState',
                'bitmapHasTextInterest',
                'markBitmapOwnersDirty',
                'retireBitmapOwners',
                'markSpriteDirty',
                'markParentDirty',
            ]),
            entries: bindScopeMethods(scope, [
                'buildTextGroups',
                'canContinueTextGroup',
                'createTextGroup',
                'createOrUpdateEntry',
                'shouldDeferSpriteEntry',
                'observeEntry',
                'observeEntryWhenVisibleOrActive',
                'requestEntryTranslation',
                'retireSpriteEntry',
                'restoreEntrySource',
                'applyRenderCommand',
                'getRenderGeneration',
                'isRenderTargetCurrent',
                'handleRenderRejected',
                'completeEntryFromCommand',
                'isEntryCommandCurrent',
                'markRecordTerminal',
                'shouldKeepRecordAfterRenderRejection',
                'isRenderApplicationFailure',
                'normalizeRenderRejectionReason',
                'isRecordActive',
                'getRecordStatus',
                'isRecordRequestActive',
                'hasRenderedTranslation',
                'getSpriteObservationStatus',
            ]),
            frame: bindScopeMethods(scope, [
                'installChildObservers',
                'installChildObserverOn',
                'wrapChildMethod',
                'observeChildAdded',
                'observeChildRemoved',
                'visitDisplayTree',
                'installFrameHooks',
                'hasFrameHooksActive',
                'ensureFrameHooks',
                'installFrameHook',
                'hasHookInChain',
                'flushFrame',
                'adoptCurrentSceneSprites',
                'adoptSpriteTree',
                'flushPendingBitmapOwnerClaims',
                'flushPendingDrawUnitsAfterSprite',
                'syncTrackedVisibility',
                'syncActiveOverlays',
                'processSpriteSurface',
                'retireAllSpriteEntries',
            ]),
            glyphCandidates: bindScopeMethods(scope, [
                'createGlyphCandidate',
                'refreshGlyphCandidateLayout',
                'collectGlyphCandidates',
                'processParentGlyphRuns',
                'buildGlyphGroups',
                'buildGlyphGroupsByChildOrder',
                'buildGlyphGroupsBySpatialLines',
                'splitGlyphSequence',
                'canContinueGlyphRun',
                'glyphsVerticallyCompatible',
            ]),
            install: bindScopeMethods(scope, [
                'install',
                'exposeAdapterApi',
                'installOrchestratorSubscription',
                'installSurfaceDrawSubscription',
                'installBitmapTextRunSubscription',
            ]),
            overlayBitmap: bindScopeMethods(scope, [
                'renderSpriteOverlay',
                'renderSpriteOverlayNow',
                'getCachedSpriteOverlayBitmap',
                'createSpriteOverlayCacheKey',
                'createSpriteOverlayEntryCacheKey',
                'roundCacheNumber',
                'invalidateBitmapOverlayCache',
                'createOverlayBitmapFromSource',
                'copySourceBitmapToOverlay',
                'clearOverlayTextRegions',
                'restoreOverlayTextRegions',
                'restoreOverlayTextRegion',
                'forEachEntryTextRegion',
                'emitTextRegion',
                'replayPaintOps',
                'replayPaintOp',
                'drawTextToBitmap',
                'getScaledDrawState',
                'shouldScaleTranslatedText',
            ]),
            overlaySprite: bindScopeMethods(scope, [
                'createOverlaySprite',
                'installOverlayRenderGuard',
                'copySpriteVisualState',
                'copySpriteColorEffects',
                'copySpriteColorEffect',
                'readSpriteVisualArray',
                'cloneVisualArray',
                'visualArraysEqual',
                'attachOverlayAfterSource',
                'hideSpriteSource',
                'restoreSpriteSource',
                'removeSpriteOverlay',
                'addSourceRenderSkipGuard',
                'removeSourceRenderSkipGuard',
                'addSourceVisualMutationGuard',
                'removeSourceVisualMutationGuard',
                'installSourceVisualMutationGuard',
                'wrapSourceVisualMutation',
                'setHiddenSourceVisualArray',
                'flushSourceVisualRefresh',
                'refreshSourceRenderSuppression',
                'installSourceRenderGuard',
                'syncSpriteOverlay',
                'shouldRenderSpriteOverlay',
                'refreshSpriteOverlayRenderable',
            ]),
            parentRunLifecycle: bindScopeMethods(scope, [
                'hideRunSources',
                'applyRunSourceSuppression',
                'restoreRunSources',
                'removeParentRun',
                'syncParentRun',
                'shouldRenderParentRunOverlay',
                'refreshParentRunRenderable',
                'computeParentRunRenderable',
                'claimGlyphGroupForRun',
                'getParentRunMap',
                'ensureParentRunState',
                'getParentRunSlotMap',
                'registerParentRunSlot',
                'findParentRunSlotMatch',
                'clearParentRunSlot',
                'isActiveParentRunSlot',
                'areParentRunSlotsCompatible',
                'isParentRunTextExtension',
                'createParentRunSlotKey',
                'parentRunLayerKey',
            ]),
            parentRunOverlay: bindScopeMethods(scope, [
                'renderParentRunOverlay',
                'computeParentRunOverlayLayout',
                'createParentRunOverlaySignature',
                'copyRunReferenceVisualState',
                'attachParentRunOverlay',
                'resolveParentRunOverlayParent',
                'ensureParentRunOverlayCarrier',
                'createParentRunOverlayCarrier',
                'syncParentRunOverlayCarrier',
                'releaseParentRunOverlayCarrier',
                'parentHasLiveRunOverlay',
            ]),
            parentRunRecords: bindScopeMethods(scope, [
                'createOrUpdateParentRun',
                'observeRun',
                'observeRunWhenVisibleOrActive',
                'requestRunTranslation',
                'completeRunFromCommand',
                'isRunCommandCurrent',
            ]),
            state: bindScopeMethods(scope, [
                'ensureSpriteState',
                'ensureBitmapState',
                'getBitmapState',
                'shouldObserveBitmapMutation',
                'activateBitmapTextInterest',
                'deactivateBitmapTextInterest',
                'refreshBitmapTextInterest',
                'isWindowOwnedBitmap',
                'isOverlayBitmap',
                'restoreTranslatedText',
                'safePrepareText',
                'applyEligibilityToSpriteRecord',
                'describeSpriteRecordEligibility',
                'logTextDetected',
                'logOverlayDraw',
                'updateItem',
            ]),
            utils: bindScopeMethods(scope, [
                'findPropertyDescriptor',
                'measureTextWidth',
                'computeFontSignature',
                'sanitizeVisibleText',
                'textUnitCount',
                'normalizeCanvasTextAlign',
                'rectCenterY',
                'verticalOverlapAmount',
                'glyphBounds',
                'rectFromDimensions',
                'isValidRect',
                'rectHasArea',
                'rectanglesOverlap',
                'bucket',
                'bucketCount',
                'getParentId',
                'finiteNumber',
                'positiveNumber',
                'pruneArray',
                'stringify',
                'safeCall',
                'isAdapterContractFailure',
                'errorMessage',
                'warn',
            ]),
            visibility: bindScopeMethods(scope, [
                'shouldPublishObservation',
                'createObservationSignature',
                'normalizeRectSignature',
                'normalizeSignatureNumber',
                'updateEntryVisibility',
                'updateRunVisibility',
                'syncRecordVisibility',
                'markRecordVisibilitySynced',
                'deactivateHiddenSpriteRecord',
                'isTerminalSpriteRecord',
                'isSpriteEntryScreenVisible',
                'isParentRunScreenVisible',
                'isSpriteSourceRenderableNow',
                'isSpriteSourceRenderableInOpenParent',
                'isDisplayObjectOpen',
                'hasPositiveOpacity',
                'hasVisibleFrame',
                'areAncestorsOpen',
                'isDisplayObjectInCurrentScene',
                'isChildInParent',
                'readFrameKey',
            ]),
        });
    }

    function bindScopeMethods(scope, names) {
        const facade = Object.create(null);
        names.forEach((name) => {
            facade[name] = (...args) => {
                const method = scope && scope[name];
                if (typeof method !== 'function') {
                    throw new Error('[SpriteText] Missing controller method: ' + name);
                }
                return method(...args);
            };
        });
        return Object.freeze(facade);
    }

            return {
                create: createSpriteTextControllerFacades,
            };
        },
    });
})();
