// Game Message adapter support: explicit controller dependency facades.
// Child controllers use these facets instead of constructing ad hoc dispatchers.
(() => {
    'use strict';

    LiveTranslatorDefine({
        name: 'adapters.gameMessage.controllerFacades',
        factory() {

    function createGameMessageControllerFacades(context = {}) {
        const callController = context.callController;
        if (typeof callController !== 'function') {
            throw new Error('[GameMessage] controller facades require a controller dispatcher.');
        }

        return Object.freeze({
            install: bindControllerMethods(callController, [
                'install',
                'hasTextOrchestrator',
                'getGameMessageForWindow',
                'isMessageWindowLike',
                'markDedicatedMessageWindow',
                'claimMessageContentsSurface',
                'drawMessageFaceIfNeeded',
                'exposeAdapterApi',
                'resolveMessageStartCoordinates',
            ]),
            evaluation: bindControllerMethods(callController, [
                'evaluateGameMessageText',
                'prepareMessageRedrawText',
                'createStreamingPreviewText',
                'stripMessageControlCodes',
                'createEvaluationGameMessage',
                'createEvaluationWindow',
            ]),
            text: bindControllerMethods(callController, [
                'resolveGameMessageTextScale',
                'resolveGameMessageOriginAwareLineBreaks',
                'resolveGameMessageDisableStreaming',
                'resolveEnableForesight',
                'createBreakToken',
                'createBreakMap',
                'countTokenOccurrences',
                'previousNonHorizontalWhitespace',
                'nextNonHorizontalWhitespace',
                'shouldJoinSoftBreakWithoutSpace',
                'collapseGameMessageSoftBreaks',
                'normalizeConvertedMessageText',
                'sanitizeRestoredMessageText',
                'createEscapeAwarePayload',
                'restoreMessageText',
                'restoreStreamingText',
                'getResolvedTextForWindow',
            ]),
            wrapping: bindControllerMethods(callController, [
                'createTextScaleScope',
                'disposeTextScaleScope',
                'ensureTextScaleScope',
                'getCurrentLineHeight',
                'canSoftWrap',
                'resetWrapPageState',
                'commitWrapLineBreak',
                'readEscapeToken',
                'isMessageWhitespace',
                'isMessageCjkCharacter',
                'tokenizeMessageText',
                'measureTokenWidth',
                'applyEscapeToken',
                'appendMeasuredText',
                'appendTextRun',
                'wrapMessageText',
                'resolveMessageStartX',
                'appendEscapeTokenForWrap',
                'appendSpaceTokenForWrap',
            ]),
            redraw: bindControllerMethods(callController, [
                'canUseNativeRender',
                'drawMessageFaceIfReady',
                'createNativeTextState',
                'flushNativeText',
                'redrawFallback',
                'redrawGameMessageText',
                'redrawMessageText',
                'isMessageWindowReadyForRedraw',
                'shouldDeferMessageRedraw',
                'applyPendingMessageRedraw',
                'createPendingRenderDecision',
                'acceptPendingMessageRender',
                'rejectPendingMessageRender',
                'clearPendingMessageRedraw',
            ]),
            session: bindControllerMethods(callController, [
                'createMessageState',
                'createMessageRenderSession',
                'getMessageState',
                'getMessageRenderSession',
                'createMessageStreamPreviewState',
                'createMessageStartState',
                'attachMessageRecordSession',
                'clearMessageRenderSession',
                'setMessageRequestSession',
                'clearMessageRequestSession',
                'setMessageRenderRetained',
                'updateMessageVisibilitySession',
                'setPendingMessageRedrawSession',
                'getPendingMessageRedrawSession',
                'clearPendingMessageRedrawSession',
                'getMessageStreamPreviewSession',
                'beginMessageStreamPreview',
                'setMessageStreamPreviewText',
                'getMessageStreamPreviewText',
                'isMessageStreamPreviewCurrent',
                'stopMessageStreamPreview',
                'clearPendingStreamPreviewSession',
                'resetStreamState',
                'getMessageStartSession',
                'clearMessageStartSession',
                'setMessageStartCoordinates',
                'getMessageStartCoordinates',
                'beginMessageSession',
                'resetWindowMessageState',
                'isSessionCurrent',
                'isCurrentTranslation',
                'getCurrentMessageSessionId',
                'setMessageTranslationSession',
                'markMessageTranslationRequested',
                'getCurrentMessagePayload',
                'setCurrentMessagePayload',
                'takeCurrentMessagePayload',
                'captureTextStateStart',
                'collectWindowsForGameMessage',
                'collectSceneMessageWindows',
                'wrapMessageContents',
                'installLifecycleHooks',
                'wrapLifecycleMethod',
                'wrapUpdateForVisibility',
                'updateMessageVisibilityFromWindow',
                'messageHasQueuedText',
                'installStartMessageHook',
                'observeStartedMessage',
                'discoverAndHookMessageWindowCtors',
                'installMessageWindowCtorHooks',
                'installProcessCharacterFallback',
                'prepareProcessCharacterPayload',
                'completeProcessCharacterFallback',
                'installProcessCompleteMessage',
            ]),
            detection: bindControllerMethods(callController, [
                'processCompleteMessage',
                'scheduleForesightTranslations',
                'collectUpcomingMessageBlocks',
            ]),
            foresightHooks: bindControllerMethods(callController, [
                'createForesightScanner',
                'installGameInterpreterExecutionContextHook',
                'installGameInterpreterChildOriginHook',
                'installGameMessageAddOriginHook',
                'installGameInterpreterMessageOriginHook',
                'installGamePlayerTransferForesightHook',
                'wrapGamePlayerTransferForesightMethod',
                'createPendingMessageOrigin',
                'attachCompletedMessageOrigin',
                'getVerifiedMessageOrigin',
                'isGameMessageAddOrigin',
            ]),
            foresightContext: bindControllerMethods(callController, [
                'attachGameMessageAddOrigin',
                'attachChildInterpreterOriginContext',
                'peekInterpreterExecutionContext',
                'createInterpreterExecutionContext',
                'createForesightFrameFromContext',
                'createChildInterpreterDescriptor',
                'getEventCommandNextIndex',
                'cloneForesightFrames',
                'cloneForesightFrame',
                'readCommonEventIdFromCommand',
                'getCommonEventData',
                'getInterpreterForesightId',
                'getInterpreterForesightListId',
                'getInterpreterCommonEventId',
                'getInterpreterCommonEventName',
                'parseMessageOriginBlock',
                'clearMessageOrigin',
                'readMessageOriginText',
                'getInterpreterOriginId',
            ]),
            foresightRecords: bindControllerMethods(callController, [
                'getGlobalGameMessage',
                'integerIndex',
                'createForesightPayload',
                'convertMessageTextForForesight',
                'requestForesightTranslation',
                'cancelForesightTranslations',
                'consumeForesightRecord',
                'pruneForesightRecords',
                'getForesightSourceKey',
                'createForesightRecordId',
                'hashTextForId',
                'applyStreamDelta',
            ]),
            clear: bindControllerMethods(callController, [
                'installGameMessageClearHook',
                'hasHookInChain',
                'clearForesightSnapshot',
                'showIntel',
                'clearRecordFields',
                'detachCurrentMessageRecord',
                'updateRecordVisibility',
            ]),
            records: bindControllerMethods(callController, [
                'installOrchestratorSubscription',
                'detectMessageRecord',
                'detectSkippedMessageRecord',
                'describeMessageEligibility',
                'createObservation',
                'createMessageRecord',
                'syncMessageRecord',
                'createRecordId',
                'getWindowId',
                'getWindowType',
                'observeMessageRecord',
                'updateItem',
                'recordDecision',
                'recordRenderCommitted',
                'recordRenderDeferred',
                'recordRenderRejected',
                'backgroundItem',
                'setRecordPriority',
                'cancelRecordTranslation',
                'setRecordVisibility',
                'retireItem',
                'resolveMessageRecord',
                'rememberRenderTarget',
                'forgetRenderTarget',
                'rememberBitmapGlyphSource',
                'rememberPendingBitmapGlyphSource',
                'forgetPendingBitmapGlyphSource',
                'forgetBitmapGlyphSource',
                'getPendingBitmapGlyphSourceKey',
                'claimMessageGlyphSource',
                'releaseBitmapGlyphSource',
                'buildBitmapGlyphSearchText',
                'normalizeGlyphSearchText',
            ]),
            render: bindControllerMethods(callController, [
                'applyRenderCommand',
                'getLifecycleRecord',
                'getRenderGeneration',
                'isRenderTargetCurrent',
                'handleRenderRejected',
                'skipRender',
                'stopStreamPreview',
                'restoreOriginalAfterStreamPreview',
                'clearCurrentRequestToken',
                'markRenderSkipped',
                'markRenderFailed',
                'markMessageRendered',
                'retireDetachedRecord',
                'handleRequestFailed',
                'handleRequestSkipped',
                'getMessageScreenState',
                'warn',
                'isAdapterContractFailure',
                'errorLog',
            ]),
        });
    }

    function bindControllerMethods(callController, names) {
        const facade = Object.create(null);
        names.forEach((name) => {
            facade[name] = (...args) => callController(name, ...args);
        });
        return Object.freeze(facade);
    }

            return {
                create: createGameMessageControllerFacades,
            };
        },
    });
})();
